//users
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const CLEAN_USER_BY_ID = 'CLEAN_USER_BY_ID';
export const UPDATE_USER = 'UPDATE_USER';

//filtros
export const FILTER_BY_SOCIAL_MEDIA = 'FILTER_BY_SOCIAL_MEDIA';
export const FILTER_BY_STATE = 'FILTER_BY_STATE';
export const SEARCH_BY_CONTACT = 'SEARCH_BY_CONTACT';

//mensajes recibidos
export const GET_ALL_MESSAGES_RECIVED = 'GET_ALL_MESSAGES_RECIVED';
export const GET_MESSAGE_RECIVED_BY_ID = 'GET_MESSAGE_RECIVED_BY_ID';
export const UPDATE_ACTIVE_MESSAGE_RECEIVED = 'UPDATE_ACTIVE_MESSAGE_RECEIVED';
export const DESACTIVATE_ALL_MESSAGES_RECEIVED = 'DESACTIVATE_ALL_MESSAGES_RECEIVED';

//mensajes enviados
export const CREATE_MESSAGE_SEND = 'CREATE_MESSAGE_SEND';

//busnisess
export const GET_BUSINESS_BY_ID = 'GET_BUSINESS_BY_ID';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';

//contactos
export const GET_CONTACT_BY_ID = 'GET_CONTACT_BY_ID';
export const GET_CONTACT_BY_MESSAGE_RECEIVED = 'GET_CONTACT_BY_MESSAGE_RECEIVED';